### ISSUE TITLE
第一次看见全中文介绍的Android库，立马star！

### ISSUE THREAD

**Issue by XhinLiang** [shichaohui/AnimRefreshRecyclerView#1]
顺便问问po主，这个
dependencies {
    compile 'com.sch.rfview:AnimRefreshRecyclerView:1.0.1'
}
是怎么做的呢。我也想写个库，但无奈不知道这个是怎么做成的。

**Comment by csh159** [comment]
想问一下可以再次基础上自定义动画样式么？

**Comment by shichaohui** [comment]
发布项目可以参考这里：http://blog.saymagic.cn/2015/02/16/release-library-to-jcenter.html

**Comment by shichaohui** [comment]
发布项目可以参考这里：http://blog.saymagic.cn/2015/02/16/release-library-to-jcenter.html.
目前是不能自定义动画的，项目中有源码，如果有需要的话可以先自己修改源码实现。
