### ISSUE TITLE
首次进入UI显示问题

### ISSUE THREAD

**Issue by hd1236** [shichaohui/AnimRefreshRecyclerView#12]
设置了
 mRecyclerView.addHeaderView(headerView);
            // 设置头部的最大拉伸倍率，默认1.5f，必须写在setHeaderImage()之前
            mRecyclerView.setScaleRatio(1.7f);
            // 设置下拉时拉伸的图片，不设置就使用默认的
            mRecyclerView.setHeaderImage((ImageView) headerView.findViewById(R.id.iv_hander));
打开app，首次进入调用mRecyclerView.setRefresh(true);
进度条和图片有覆盖情况怎么搞？

**Comment by loveskill** [comment]
这个问题必须去修改源码中的AnimView的自定义控件中的onDraw()方面，把原来的代码改为：@Override
    protected void onDraw(Canvas canvas) {
        mCanvas = canvas;
        if (isShow) {
            // 画圆
            if (animRadius < radius) {
                start();
            } else {
                canvas.drawCircle(centerPointX, centerPointY, radius, paint);
                sweepAngle += 2;
                startAngle = sweepAngle >= 359 ? START_ANGLE : startAngle + SPEED;
                sweepAngle = sweepAngle >= 359 ? START_ANGLE : sweepAngle;
                // 画弧
                canvas.drawArc(oval, startAngle, sweepAngle, false, hollowPaint);
            }
        } else {
            end();
        }
        // 重绘
        invalidate();
    } 就可以了
