### ISSUE TITLE
关于非上拉与下拉刷新方式加载数据的问题

### ISSUE THREAD

**Issue by wsf5918** [shichaohui/AnimRefreshRecyclerView#3]
发现一个问题，就是我使用上拉与下拉刷新的时候，可以正常的加载相关的数据，以及显示的显示。

但是，我本地产生的一些数据，我通过向数据集中添加数据时。再通过Adapter通过数据变更时，却无法展示最新的加载的数据。
![image](https://cloud.githubusercontent.com/assets/5617446/9543337/cc742fc4-4daa-11e5-977f-4d05c192226c.png)

这个是我调用的方式。

**Comment by shichaohui** [comment]
刷新或增删数据时，使用animRefreshView.getAdapter()获取Adapter，然后使用获取到的Adapter更新数据。

**Comment by wsf5918** [comment]
非常谢谢，那个方法是可以有效，但我觉得有点奇怪的是，应该是animRefreshView.getAdapter()取回来的对象，应该就是mStaggeredHomeAdapter啊，他们的地址应该是一样的。不过现在问题解决了。非常谢谢。能加你的QQ吗哥们？2831668236

**Comment by shichaohui** [comment]
因为在有Header或者Footer 的时候AnimRefreshRecyclerView就会对Adapter进行重新包装，所以Adapter可能会改变。
