### ISSUE TITLE
似乎和自定义的onItemClick冲突

### ISSUE THREAD

**Issue by quhung** [shichaohui/AnimRefreshRecyclerView#6]
下拉刷新似乎和自定义的onItemClick冲突，有没有什么办法解决啊？？？

**Comment by shengbox** [comment]
下拉刷新似乎和自定义的onItemClick冲突，有没有什么办法解决啊？？？

**Comment by nadazero** [comment]
我也遇到了这个问题，这个问题很严重啊，因为Item不可能不做click处理吧。
这是个致命的问题，如果不解决，这个控件就不能用了

**Comment by xmfei229** [comment]
解决了没有？这个问题？是什么原因造成的呢？

**Comment by 354420603** [comment]
只是一个致命的缺陷，设置监听的时候回跟下拉刷新起冲突，希望能解决

**Comment by quhung** [comment]
如果不是用StaggeredGridLayoutManager的话，可以用：
`
public class RecyclerViewClickSupporter implements RecyclerView.OnChildAttachStateChangeListener,
        View.OnClickListener {

    private final RecyclerView mRecyclerView;
    private OnItemClickListener mOnItemClickListener;

    public RecyclerViewClickSupporter(RecyclerView recyclerView) {
        if (recyclerView == null)
            throw new IllegalArgumentException("the RecyclerView that will be attached can't be null");
        this.mRecyclerView = recyclerView;
    }

    public void attach(OnItemClickListener onItemClickListener) {
        attachToRecyclerView();
        setOnItemClickListener(onItemClickListener);
    }

    public void detach() {
        detachToRecyclerView();
    }

    private void setOnItemClickListener(OnItemClickListener onItemClickListener) {
        this.mOnItemClickListener = onItemClickListener;
    }

    private void attachToRecyclerView() {
        mRecyclerView.addOnChildAttachStateChangeListener(this);
    }


    private void detachToRecyclerView() {
        mRecyclerView.removeOnChildAttachStateChangeListener(this);
    }

    @Override
    public void onChildViewAttachedToWindow(View view) {
        if (view != null) {
            view.setOnClickListener(this);
        }
    }

    @Override
    public void onChildViewDetachedFromWindow(View view) {
        if (view != null) {
            view.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View v) {
        if (mOnItemClickListener != null) {
            RecyclerView.ViewHolder holder = mRecyclerView.getChildViewHolder(v);
            mOnItemClickListener.onItemClicked(mRecyclerView, holder.getAdapterPosition(), v);
        }
    }

    public interface OnItemClickListener {
        void onItemClicked(RecyclerView recyclerView, int position, View v);
    }
}
`
创建一个`RecyclerViewClickSupporter`,然后attach就行了

**Comment by quhung** [comment]
如果不是用StaggeredGridLayoutManager的话，可以用：
`

public class RecyclerViewClickSupporter implements RecyclerView.OnChildAttachStateChangeListener,
View.OnClickListener {
private final RecyclerView mRecyclerView;
private OnItemClickListener mOnItemClickListener;

public RecyclerViewClickSupporter(RecyclerView recyclerView) {
    if (recyclerView == null)
        throw new IllegalArgumentException("the RecyclerView that will be attached can't be null");
    this.mRecyclerView = recyclerView;
}

public void attach(OnItemClickListener onItemClickListener) {
    attachToRecyclerView();
    setOnItemClickListener(onItemClickListener);
}

public void detach() {
    detachToRecyclerView();
}

private void setOnItemClickListener(OnItemClickListener onItemClickListener) {
    this.mOnItemClickListener = onItemClickListener;
}

private void attachToRecyclerView() {
    mRecyclerView.addOnChildAttachStateChangeListener(this);
}


private void detachToRecyclerView() {
    mRecyclerView.removeOnChildAttachStateChangeListener(this);
}

@Override
public void onChildViewAttachedToWindow(View view) {
    if (view != null) {
        view.setOnClickListener(this);
    }
}

@Override
public void onChildViewDetachedFromWindow(View view) {
    if (view != null) {
        view.setOnClickListener(null);
    }
}

@Override
public void onClick(View v) {
    if (mOnItemClickListener != null) {
        RecyclerView.ViewHolder holder = mRecyclerView.getChildViewHolder(v);
        mOnItemClickListener.onItemClicked(mRecyclerView, holder.getAdapterPosition(), v);
    }
}

public interface OnItemClickListener {
    void onItemClicked(RecyclerView recyclerView, int position, View v);
}
}

`
创建一个RecyclerViewClickSupporter,然后attach就行了
